---
- hosts: ansible_hosts 
  become: yes
  tasks:
  
  - name: system uptime
    command: uptime
    register: uptime    


  - name: system hostname 
    command: hostname
    register: hostname

  - debug: var={{ item }}
    loop:
      - uptime.stdout
      - hostname.stdout  
