##commenting out a line using ansible
---
- hosts: localhost
  become: yes
  vars:
  - /etc/httpd/conf/
  tasks: 
  - name: commenting a line in /etc/httpd/conf/httpd.conf
    lineinfile:
      path: "{{ dir }}/httpd.conf"
      #the string to search for comment 
      regexp: '(^EnableSendfile)'
      #commentoutthisline
      line: '# \1'
      state: present
      backup: yes
      backrefs: yes


     