##commenting out a line using ansible
---
- hosts: localhost
  become: yes
  vars:
  - dir: /etc/httpd/conf/ 
  tasks: 
  - name: commenting a line in /etc/httpd/conf/httpd.conf
    lineinfile:
      path: "{{ dir }}/httpd.conf"
      #the string to search for comment 
      regexp: '(^EnableMMAP and EnableSendfile: On systems that support it,)'
      #commentoutthisline
      line: '# \1'
      state: present
      backup: yes
      backrefs: yes


     
