---
- hosts: localhost
  become: yes
  gather_facts: yes
  tasks:

  - name: fail task when the command error output print failed
    command: /usr/bin/example-command -x -y -z
    register: command_result
    failed_when: "FAILED' in command_result.stderr"
   
  - name: 
    debug:
      msg: "{{ command_result }}"  
