---
- hosts: localhost
  become: yes
  gather_facts: yes
  vars:
  - directory: /home/ansible/working/
  tasks:
  - block:  
    - name: finding files in /home/ansible/working
      command: "ls /home/ansible/working/phantom.txt" 
      register: list_out
    rescue:
    - debug: 
        msg: "this is not a valid path /home/ansible/working"
    always: 
    - debug:
        msg: "This will always execute"    
