---
- hosts: ansible_hosts
  become: yes
  tasks:
  - name: installing git 
    yum:
      name: git
      state: latest

  - name: cloning my git repo to my remote hosts
    git: 
      repo: https://github.com/youngkingtaco/Test_newrepo.git  
      dest: /etc/ansible/test_repo
