---
- hosts: localhost
  become: yes
  gather_facts: yes 
  tasks:
  - name: install httpd 
    yum: 
      name: httpd 
      state: latest
    notify: restart httpd
  
  - name: modify the permissions in /var/www/html
    file:
      path: /var/www/html/
      owner: root
      group: root
      mode: '0777'  

  - name: adding a new message to index.html
    shell: echo "Hi! this is hugo" > /var/www/html/index.html
    when: ansible_os_family == "RedHat" 

  handlers:
  - name: restart httpd services
    service: 
      name: httpd
      state: started
    listen: restart httpd  
