---
- hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
  
  - name: install apache
    yum: 
     name: httpd
     state: latest

  - name: replace index.html
    copy: 
      dest: /var/www/html/index.html
      content: "Hi I am host {{ item }} and I run the linux kernel {{ item }}\n"
    with_items:
    - ansible_hostname
    - ansible_kernel      
    register: index_file

  - name: output index.html 
    debug: 
      msg: "{{ index_file }}" 
