---
- hosts: localhost
  become: yes
  gather_facts: yes 
  tasks:
  - name: install httpd 
    yum: 
      name: httpd 
      state: latest
    notify: restart httpd
  
  handlers:
  - name: start httpd services 
    service: 
      name: httpd 
      state: started
    listen: restart httpd       

  - name: 
    lineinfile: 
      path: /var/www/html/index.html
      line: "Hello, This is Hugo"          
