---  ##installing tomcat on my webserver inventory 
- name: install tomcat server 
  hosts: ansible_hosts
  become: true 
  vars:
  - tomcat_url:  http://apachemirror.wuchna.com/tomcat/tomcat-9/v9.0.26/bin/apache-tomcat-9.0.26.tar.gz
  - tomcat_package: apache-tomcat-9.0.26
  
  tasks:
  - name: install java 
    yum:
      name: java-11-openjdk-devel
      state: present 

  - name: download tomcat server packages 
    get_url: 
      url: "{{ tomcat_url }}"
      dest: /usr/local

  - name: extract tomcat packages 
    unarchive: 
      src: /usr/local/{{ tomcat_package }}.tar.gz
      dest: /usr/local 
      remote_src: yes

  - name: start tomcat services
    shell: nohup /usr/local/{{ tomcat_package }}/bin/startup.sh    
