---##example of using with gather_facts - to gather variables from the setup module
- hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
  
  - name: installing apache
    when: ansible_distribution == "CentOS"
    yum:
     name: httpd
     state: latest
  
  - name: installing apache
    when: ansible_distribution == "RedHat" 
    yum: 
     name: postgresql
     state: latest  
