-- ##This playbook will install httpd, and postgresql packages across our ansible_hosts inventory-
- hosts: ansible_hosts
  become: yes
  tasks:

  - name: ensure apache is running at the latest version
    yum: 
      name: httpd
      state: latest
  - name: make sure that apache is enabled 
    service: 
      name: httpd
      enabled: true  
  - name: Write it to a index html filee
    copy: 
      src: /var/www/html/index.html
      dest: /var/www/html/
  - name: ensure postgresql is at the latest version 
    yum:
      name: postgresql
      state: latest 
  - name: ensure that postgresql has started
    service:
      name: postgresql 
      state: started
      enabled: true  
