---
- hosts: ansible_hosts 
  become: yes
  tasks:
  
  - name: push the script only if the OS is redhat
    copy:
      src: /usr/scripts/resize_dynamic_files.sh
      dest: /usr/scripts
      owner: root
      group: root
      mode: '0755'
    when: ansible_os_family == "RedHat" 
