---
- hosts: ansible_hosts
  become: yes
  tasks:

  - name: removing httpd package install
    yum: 
      name: httpd
      state: absent 
  - name: removing postgresql package
    yum: 
      name: postgresql
      state: absent    
