## add a line if that line doesn't exist in the path that you provided
---
- hosts: localhost
  become: yes
  tasks:
  - name: add a line if it doesn't exist 
    lineinfile:
      path: "/tmp/users.txt"
      #the string to search
      regexp: "#html_directory = no"
      line: "html_directory = yes"
      state: present
      backup: yes
