---
- hosts: ansible_hosts
  become: yes
  tasks:
  - name: replacing a line, and substitute it
    lineinfile: 
      path: /tmp/hosts
      regexp:'127.0.0.1'
      line: 127.0.0.1 localhost
      owner: root
      group: root
      mode: '0644'    
