---
- hosts: localhost
  tasks: 
    - name: create working directory
      file: 
        name: "{{ working_dir }}"
        state: directory 

    - name: write service list 
      lineinfile: 
        path: "{{ working_dir }}/service.txt" 
        create: yes
        line: "{{ service_list }}"
    
    - name: view share property 
      command: ls -la "{{ share_paths['nfs'] }}"
      register: cmd_output 
    
    - name: write command module output to file 
      copy: 
        content: "{{ cmd_output }}"
        dest: "{{ working_dir }}/cmd_output.txt"
