---
- hosts: localhost
  become: yes
  vars:
    dir: /tmp/ansible_dir/
    text_file: user_scripts_count.sh
  vars_prompt:
    name: YES 
    prompt: "do you really want this playbook to execute?" 
  gather_facts: yes
  tasks:
    - name: debug message module
      debug:
        msg: "Creating directory, and script"
    
    - name: creating directory /tmp/ansible_dir 
      file: 
        path: /tmp/ansible_dir/ 
        state: directory 
        mode: '0777'
        owner: root
        group: root 
    
    - name: creating file users_script_count.sh 
      file: 
        path: /tmp/ansible_dir/
        state: touch 
        mode: '0775'
        owner: root
        group: root 
            



      