---
- hosts: ansible_hosts
  become: true
  become_user: xhcalderone
  tasks:
          
  - name: add the exclude line to the yum-cron.conf
    lineinfile:
      path: /etc/yum.conf/
      line: exclude = cups*
